model_2_feature_names = ['title',
	'titles_lag',
	'world',
	'event_code_3121_count',
	'event_code_3021_count',
	'current_title_count',
	'assess_titles_lag',
	'event_code_4020_count',
	'accuracies_mean',
	'current_world_mean_time',
	'event_code_4025_count',
	'event_code_4030_count',
	'event_code_4090_count',
	'event_code_2010_count',
	'accumulated_accuracy',
	'event_code_3010_count',
	'all_types_accumulated_uncorrect_attempts',
	'accumulated_accuracy_group',
	'title_event_code_Sandcastle Builder (Activity)_4020_count',
	'total_time_lag',
	'time_per_event',
	'session_activity_len_lag_diff',
	'total_time_lag_diff',
	'accuracies_std',
	'event_code_2010_count_Time_norm',
	'day_sin',
	'accuracies_median',
	'assess_duration_lag',
	'event_code_3120_count_Time_norm',
	'event_code_3020_count_Time_norm',
	'accuracy_groups_std',
	'title_Crystal Caves - Level 3_count_Time_norm',
	'current_title_total_time',
	'event_code_4035_count_Time_norm',
	'assess_duration_min',
	'event_code_4025_count_Time_norm',
	'accumulated_misses',
	'title_event_code_Cauldron Filler (Assessment)_4025_count',
	'title_event_code_Happy Camel_3120_count',
	'world_TREETOPCITY_count',
	'world_CRYSTALCAVES_count',
	'title_Crystal Caves - Level 2_count',
	'accumulated_uncorrect_attempts_mean',
	'current_world_total_time',
	'event_code_4020_count_Time_norm',
	'title_event_code_Cart Balancer (Assessment)_4070_count',
	'title_event_code_Bottle Filler (Activity)_4070_count',
	'title_Welcome to Lost Lagoon!_count_Time_norm',
	'ratio_of_life_in_game',
	'title_event_code_Happy Camel_4070_count',
	'title_Crystal Caves - Level 1_count',
	'title_event_code_Sandcastle Builder (Activity)_4035_count',
	'accumulated_uncorrect_attempts_std',
	'accumulated_sessions',
	'hour_cos',
	'event_code_4022_count',
	'event_code_4030_count_Time_norm',
	'title_Magma Peak - Level 1_count',
	'event_code_4022_count_Time_norm',
	'last_accuracy_Bird Measurer (Assessment)',
	'assess_duration_lag_diff',
	'title_event_code_Pan Balance_3020_count',
	'accumulated_correct_attempts_mean',
	'title_event_code_All Star Sorting_3120_count',
	'last_accuracy_Cauldron Filler (Assessment)',
	'accuracies_sum',
	'title_event_code_Crystal Caves - Level 3_2000_count_Time_norm',
	'event_code_2060_count',
	'type_Game_count_Time_norm',
	'assess_duration_median',
	'title_event_code_Bug Measurer (Activity)_4035_count',
	'0_group_count',
	'last_accuracy_Chest Sorter (Assessment)',
	'event_code_4040_count_Time_norm',
	'title_event_code_Chow Time_3121_count',
	'event_code_4100_count_Time_norm',
	'title_Magma Peak - Level 1_count_Time_norm',
	'total_time_max',
	'event_code_2080_count',
	'sec_since_installation',
	'title_event_code_Chest Sorter (Assessment)_4025_count',
	'title_event_code_Egg Dropper (Activity)_4070_count_Time_norm',
	'title_event_code_Chest Sorter (Assessment)_4020_count',
	'title_Tree Top City - Level 1_count_Time_norm',
	'type_Clip_count',
	'title_event_code_Cart Balancer (Assessment)_4070_count_Time_norm',
	'type_Activity_count_Time_norm',
	'world_MAGMAPEAK_count_Time_norm',
	'title_Ordering Spheres_count',
	'title_Magma Peak - Level 2_count_Time_norm',
	'total_time_std',
	'event_code_2000_count',
	'title_event_code_Tree Top City - Level 1_2000_count',
	'title_event_code_Welcome to Lost Lagoon!_2000_count',
	'title_event_code_Sandcastle Builder (Activity)_4070_count',
	'title_event_code_Sandcastle Builder (Activity)_4035_count_Time_norm',
	'world_CRYSTALCAVES_count_Time_norm',
	'Sandcastle Builder (Activity)_title_total_time',
	'title_event_code_Tree Top City - Level 3_2000_count',
	'title_event_code_All Star Sorting_2025_count',
	'title_event_code_Tree Top City - Level 2_2000_count',
	'title_event_code_Egg Dropper (Activity)_4070_count',
	'title_Crystal Caves - Level 2_count_Time_norm',
	'title_event_code_Sandcastle Builder (Activity)_3010_count',
	'event_code_4045_count',
	'title_event_code_Crystal Caves - Level 2_2000_count',
	'total_time_mean',
	'title_event_code_Cauldron Filler (Assessment)_4070_count',
	'title_event_code_Chow Time_3021_count',
	'accuracies_lag_diff',
	'title_event_code_All Star Sorting_2030_count',
	'title_Bottle Filler (Activity)_count',
	'title_event_code_Chest Sorter (Assessment)_3021_count',
	'event_code_2035_count',
	'title_event_code_Chest Sorter (Assessment)_4030_count',
	'session_activity_len_mean',
	'title_event_code_Fireworks (Activity)_4070_count',
	'event_code_4021_count',
	'title_event_code_Welcome to Lost Lagoon!_2000_count_Time_norm',
	'title_event_code_Scrub-A-Dub_4010_count',
	'event_code_4010_count_Time_norm',
	'title_Crystal Caves - Level 1_count_Time_norm',
	'all_types_accumulated_correct_attempts',
	'event_code_2080_count_Time_norm',
	'title_event_code_Sandcastle Builder (Activity)_4021_count',
	'title_Lifting Heavy Things_count',
	'title_event_code_Pan Balance_3120_count',
	'type_Assessment_count',
	'title_event_code_Fireworks (Activity)_3010_count',
	'event_code_2020_count_Time_norm',
	'title_event_code_Magma Peak - Level 2_2000_count',
	'title_event_code_Flower Waterer (Activity)_4070_count',
	'time_per_session',
	'title_event_code_Fireworks (Activity)_3110_count',
	'3_group_count_Time_norm',
	'title_event_code_Chow Time_2030_count',
	'title_event_code_Egg Dropper (Activity)_4020_count',
	'title_event_code_Leaf Leader_2030_count',
	'title_Scrub-A-Dub_count',
	'title_event_code_Watering Hole (Activity)_4070_count',
	'event_code_4070_count_Time_norm',
	'event_code_3110_count_Time_norm',
	'title_Tree Top City - Level 3_count_Time_norm',
	'accuracies_lag',
	'title_Egg Dropper (Activity)_count',
	'title_event_code_All Star Sorting_4035_count',
	'event_code_2083_count',
	'title_Sandcastle Builder (Activity)_count',
	'title_event_code_Sandcastle Builder (Activity)_4030_count',
	'event_code_3010_count_Time_norm',
	'event_code_2075_count',
	'days_since_installation',
	'assess_duration_max',
	'title_event_code_Crystal Caves - Level 2_2000_count_Time_norm',
	'title_Tree Top City - Level 2_count_Time_norm',
	'title_event_code_Crystal Caves - Level 1_2000_count',
	'title_event_code_Fireworks (Activity)_4030_count',
	'title_event_code_Bottle Filler (Activity)_4070_count_Time_norm',
	'title_event_code_Chest Sorter (Assessment)_4020_count_Time_norm',
	'0_group_count_Time_norm',
	'title_event_code_Scrub-A-Dub_2000_count',
	'title_event_code_Chest Sorter (Assessment)_3121_count',
	'title_event_code_Tree Top City - Level 1_2000_count_Time_norm',
	'events_per_session',
	'title_event_code_Fireworks (Activity)_4020_count',
	'title_event_code_Crystals Rule_3120_count',
	'event_code_2083_count_Time_norm',
	'event_code_4021_count_Time_norm',
	'title_Balancing Act_count',
	'MAGMAPEAK_world_activity_time',
	'title_event_code_Sandcastle Builder (Activity)_3110_count',
	'title_event_code_Chow Time_4035_count',
	'CRYSTALCAVES_world_game_time',
	'title_event_code_Magma Peak - Level 1_2000_count',
	'title_event_code_Air Show_3021_count',
	'title_Slop Problem_count_Time_norm',
	'title_event_code_Leaf Leader_3021_count',
	'Cart Balancer (Assessment)_title_total_time',
	'event_code_2060_count_Time_norm',
	'weekday_sin',
	'world_TREETOPCITY_count_Time_norm',
	'title_event_code_Magma Peak - Level 2_2000_count_Time_norm',
	'CRYSTALCAVES_world_total_time',
	'title_event_code_Cauldron Filler (Assessment)_4100_count',
	'event_code_4095_count',
	'title_event_code_Cart Balancer (Assessment)_4020_count',
	'assess_duration_std',
	'title_event_code_Crystals Rule_3020_count',
	'title_event_code_Cart Balancer (Assessment)_4100_count',
	'title_event_code_Chow Time_4070_count_Time_norm',
	'Bottle Filler (Activity)_title_total_time',
	'title_event_code_Bubble Bath_3020_count',
	'current_world_count_Time_norm',
	'world_NONE_count_Time_norm',
	'title_event_code_Tree Top City - Level 2_2000_count_Time_norm',
	'title_event_code_Happy Camel_4035_count',
	'title_event_code_Bottle Filler (Activity)_4035_count',
	'title_event_code_Ordering Spheres_2000_count',
	'title_event_code_Magma Peak - Level 1_2000_count_Time_norm',
	'title_event_code_Mushroom Sorter (Assessment)_4070_count']


model_3_feature_names = ['title',
	'accuracy_groups_skew',
	'title_Tree Top City - Level 3_count',
	'session_activity_len_lag',
	'event_code_4100_count',
	'current_world_activity_time',
	'event_code_4010_count',
	'assess_duration_mean',
	'day_cos',
	'title_Welcome to Lost Lagoon!_count',
	'event_code_3121_count_Time_norm',
	'titles_mode',
	'current_world_game_time',
	'session_activity_len_skew',
	'event_code_4035_count',
	'title_Magma Peak - Level 2_count',
	'world_MAGMAPEAK_count',
	'event_code_2030_count_Time_norm',
	'total_time_skew',
	'title_Tree Top City - Level 1_count',
	'title_Tree Top City - Level 2_count',
	'type_Game_count',
	'current_world_count',
	'event_code_4090_count_Time_norm',
	'current_title_mean_time',
	'title_Crystal Caves - Level 3_count',
	'3_group_count',
	'event_code_3021_count_Time_norm',
	'title_event_code_Cauldron Filler (Assessment)_3020_count',
	'title_event_code_Crystal Caves - Level 3_2000_count',
	'title_event_code_Sandcastle Builder (Activity)_4020_count_Time_norm',
	'event_code_4070_count',
	'current_title_count_Time_norm',
	'event_code_3120_count',
	'session_activity_len_max',
	'title_event_code_Chow Time_4070_count',
	'event_code_3110_count',
	'last_mean_accuracy',
	'title_event_code_Cauldron Filler (Assessment)_3120_count',
	'accuracy_groups_mean',
	'event_code_2025_count',
	'hour_sin',
	'type_Activity_count',
	'event_code_3020_count',
	'accuracies_skew',
	'title_event_code_Happy Camel_3020_count',
	'event_code_2030_count',
	'event_code_2020_count',
	'session_activity_len_std',
	'change_type_count',
	'event_code_4040_count',
	'event_code_2081_count',
	'title_event_code_Crystal Caves - Level 1_2000_count_Time_norm',
	'event_code_2075_count_Time_norm',
	'accuracy_groups_median',
	'title_event_code_Chicken Balancer (Activity)_4020_count',
	'title_Ordering Spheres_count_Time_norm',
	'MAGMAPEAK_world_total_time',
	'title_event_code_Scrub-A-Dub_3020_count',
	'title_event_code_Chow Time_3121_count_Time_norm',
	'sessions_per_day',
	'title_Chow Time_count',
	'title_event_code_Bird Measurer (Assessment)_2030_count',
	'type_Assessment_count_Time_norm',
	'mean_time_per_day',
	'event_code_4095_count_Time_norm',
	'world_NONE_count',
	'title_event_code_Dino Dive_2030_count',
	'All Star Sorting_title_total_time',
	'title_event_code_Chest Sorter (Assessment)_4025_count_Time_norm',
	'events_per_day',
	'title_event_code_Chow Time_3021_count_Time_norm',
	'title_event_code_Sandcastle Builder (Activity)_2000_count',
	'title_event_code_Scrub-A-Dub_3120_count',
	'title_event_code_Chest Sorter (Assessment)_3021_count_Time_norm',
	'title_event_code_Dino Drink_4070_count',
	'title_event_code_Bird Measurer (Assessment)_3021_count',
	'TREETOPCITY_world_activity_time',
	'weekday_5',
	'title_event_code_Mushroom Sorter (Assessment)_2010_count',
	'accumulated_correct_attempts_std',
	'assess_duration_sum',
	'Chow Time_title_total_time',
	'title_event_code_Bug Measurer (Activity)_4025_count',
	'title_event_code_Watering Hole (Activity)_4021_count',
	'title_Slop Problem_count',
	'title_event_code_Leaf Leader_3121_count',
	'title_event_code_Bug Measurer (Activity)_4035_count_Time_norm',
	'title_event_code_Flower Waterer (Activity)_4020_count',
	'title_event_code_Happy Camel_3121_count',
	'title_event_code_Slop Problem_2000_count_Time_norm',
	'title_event_code_Cart Balancer (Assessment)_4030_count',
	'title_event_code_Sandcastle Builder (Activity)_4070_count_Time_norm',
	'title_event_code_Bug Measurer (Activity)_4070_count',
	'title_event_code_Pan Balance_3020_count_Time_norm',
	'title_event_code_Happy Camel_4045_count',
	'title_event_code_Flower Waterer (Activity)_4022_count_Time_norm',
	'title_event_code_All Star Sorting_3021_count',
	'title_event_code_Chow Time_3010_count',
	'title_event_code_Chest Sorter (Assessment)_2010_count',
	'title_event_code_Air Show_3121_count',
	"title_Pirate's Tale_count_Time_norm",
	'title_event_code_All Star Sorting_3020_count',
	'accumulated_actions',
	'title_Sandcastle Builder (Activity)_count_Time_norm',
	'title_Fireworks (Activity)_count',
	'title_event_code_Fireworks (Activity)_3010_count_Time_norm',
	'CRYSTALCAVES_world_activity_time',
	'title_event_code_Cart Balancer (Assessment)_4035_count',
	'accumulated_uncorrect_attempts_sum',
	'title_event_code_Pan Balance_3120_count_Time_norm',
	'event_code_2070_count',
	'title_Rulers_count_Time_norm',
	'Chest Sorter (Assessment)_title_total_time',
	'title_event_code_Flower Waterer (Activity)_3010_count',
	'title_event_code_Cauldron Filler (Assessment)_4070_count_Time_norm',
	'title_event_code_Cauldron Filler (Assessment)_4035_count',
	'title_event_code_Cauldron Filler (Assessment)_3120_count_Time_norm',
	'event_code_2025_count_Time_norm',
	'TREETOPCITY_world_total_time',
	'title_event_code_Air Show_2030_count',
	'title_event_code_Sandcastle Builder (Activity)_3010_count_Time_norm',
	'title_event_code_Chow Time_2030_count_Time_norm',
	'1_group_count',
	'title_Lifting Heavy Things_count_Time_norm',
	'title_event_code_Bird Measurer (Assessment)_3121_count',
	'title_event_code_Chow Time_2020_count',
	'accuracy_groups_lag_1',
	'title_event_code_Bottle Filler (Activity)_2000_count',
	'title_Scrub-A-Dub_count_Time_norm',
	'title_event_code_Mushroom Sorter (Assessment)_2010_count_Time_norm',
	'title_event_code_Chest Sorter (Assessment)_4040_count',
	'title_event_code_Chow Time_4010_count',
	'title_event_code_Chow Time_3110_count',
	'title_event_code_All Star Sorting_4020_count',
	'event_code_2070_count_Time_norm',
	'title_event_code_Slop Problem_2000_count',
	'title_event_code_Cart Balancer (Assessment)_2010_count',
	'title_event_code_Sandcastle Builder (Activity)_4030_count_Time_norm',
	'title_event_code_Chest Sorter (Assessment)_4070_count',
	'title_event_code_Cauldron Filler (Assessment)_4030_count',
	'title_event_code_Mushroom Sorter (Assessment)_3020_count',
	'title_event_code_Fireworks (Activity)_3110_count_Time_norm',
	'total_time_median',
	'title_event_code_Flower Waterer (Activity)_3110_count',
	'title_event_code_Fireworks (Activity)_4020_count_Time_norm',
	'session_activity_len_median',
	'title_Chest Sorter (Assessment)_count',
	'title_event_code_Flower Waterer (Activity)_4025_count',
	'Dino Drink_title_total_time',
	'title_event_code_Flower Waterer (Activity)_4022_count',
	'title_event_code_Cauldron Filler (Assessment)_3020_count_Time_norm',
	'title_event_code_Chest Sorter (Assessment)_3121_count_Time_norm',
	'last_accuracy_group_Bird Measurer (Assessment)',
	'title_event_code_Balancing Act_2000_count',
	'MAGMAPEAK_world_game_time',
	'title_event_code_Cauldron Filler (Assessment)_4020_count',
	'weekday_4',
	'title_event_code_Chicken Balancer (Activity)_4035_count',
	'title_event_code_Watering Hole (Activity)_3010_count',
	'assess_titles_mode',
	'title_event_code_Leaf Leader_4070_count',
	'type_Clip_count_Time_norm',
	'weekday_3',
	'title_event_code_Sandcastle Builder (Activity)_4021_count_Time_norm',
	'title_event_code_Pan Balance_4010_count',
	'title_Cart Balancer (Assessment)_count',
	'title_event_code_Watering Hole (Activity)_4070_count_Time_norm',
	'titles_nunique',
	'TREETOPCITY_world_game_time',
	'title_event_code_Cart Balancer (Assessment)_4035_count_Time_norm',
	'title_event_code_Chicken Balancer (Activity)_4030_count',
	'event_code_2035_count_Time_norm',
	'title_event_code_Bird Measurer (Assessment)_2010_count',
	'title_event_code_Chow Time_3020_count',
	'weekday_0',
	'last_accuracy_group_Cauldron Filler (Assessment)',
	'title_Pan Balance_count',
	'event_code_4045_count_Time_norm',
	'title_event_code_Scrub-A-Dub_4010_count_Time_norm',
	'title_event_code_All Star Sorting_3110_count',
	'title_event_code_Rulers_2000_count_Time_norm',
	'title_event_code_Fireworks (Activity)_4070_count_Time_norm',
	'title_event_code_All Star Sorting_3121_count',
	'title_Chest Sorter (Assessment)_count_Time_norm',
	'title_event_code_Cart Balancer (Assessment)_2000_count',
	'last_accuracy_group_Chest Sorter (Assessment)',
	'title_event_code_Scrub-A-Dub_4070_count',
	'title_event_code_Happy Camel_3121_count_Time_norm',
	'accuracy_groups_sum',
	'event_code_2081_count_Time_norm',
	'accuracy_groups_lag_diff',
	'title_Rulers_count',
	'title_event_code_Watering Hole (Activity)_3110_count',
	'title_event_code_Mushroom Sorter (Assessment)_3020_count_Time_norm',
	'title_event_code_Bottle Filler (Activity)_2030_count',
	'title_event_code_Chicken Balancer (Activity)_4070_count',
	'title_event_code_Tree Top City - Level 3_2000_count_Time_norm',
	'Cauldron Filler (Assessment)_title_total_time',
	'title_event_code_Mushroom Sorter (Assessment)_2030_count',
	'assess_duration_skew',
	'title_event_code_Lifting Heavy Things_2000_count',
	'title_event_code_Dino Dive_3120_count',
	'title_event_code_Cart Balancer (Assessment)_3020_count_Time_norm',
	'Fireworks (Activity)_title_total_time',
	'title_event_code_All Star Sorting_4070_count',
	'title_Costume Box_count',
	'Flower Waterer (Activity)_title_total_time',
	'last_accuracy_Mushroom Sorter (Assessment)',
	'title_Balancing Act_count_Time_norm',
	'title_event_code_Dino Drink_3020_count',
	'weekday_cos',
	'title_event_code_Happy Camel_2030_count',
	'title_event_code_Watering Hole (Activity)_4025_count',
	'title_event_code_Mushroom Sorter (Assessment)_3120_count',
	'event_code_4220_count_Time_norm',
	'title_event_code_Cart Balancer (Assessment)_3021_count',
	'title_event_code_Sandcastle Builder (Activity)_3110_count_Time_norm',
	'title_event_code_Mushroom Sorter (Assessment)_4100_count',
	'title_event_code_All Star Sorting_2020_count',
	'title_event_code_Fireworks (Activity)_2000_count',
	'title_event_code_Flower Waterer (Activity)_4030_count',
	'hour_20',
	'title_event_code_Chow Time_4020_count',
	'title_event_code_Leaf Leader_4070_count_Time_norm',
	'title_event_code_Chest Sorter (Assessment)_4030_count_Time_norm',
	'title_Watering Hole (Activity)_count',
	'title_event_code_Cart Balancer (Assessment)_2010_count_Time_norm',
	'title_event_code_Pan Balance_2030_count',
	'title_event_code_Mushroom Sorter (Assessment)_3120_count_Time_norm',
	'title_event_code_Cart Balancer (Assessment)_3010_count',
	'1_group_count_Time_norm',
	'title_event_code_Dino Dive_3020_count',
	'title_event_code_Bubble Bath_3120_count',
	'title_Bird Measurer (Assessment)_count',
	'title_event_code_Cart Balancer (Assessment)_3110_count',
	'Mushroom Sorter (Assessment)_title_total_time',
	'title_event_code_Ordering Spheres_2000_count_Time_norm',
	'title_event_code_Scrub-A-Dub_4070_count_Time_norm',
	'title_event_code_Happy Camel_3120_count_Time_norm',
	'title_Cauldron Filler (Assessment)_count',
	'title_event_code_All Star Sorting_3010_count',
	'title_event_code_Bug Measurer (Activity)_4070_count_Time_norm',
	'title_event_code_Chow Time_3120_count',
	'title_event_code_Happy Camel_4045_count_Time_norm',
	'title_event_code_Mushroom Sorter (Assessment)_4030_count',
	'title_event_code_Dino Drink_4010_count',
	'session_activity_len_sum',
	'Watering Hole (Activity)_title_total_time',
	'accumulated_correct_attempts_skew',
	'title_Heavy_ Heavier_ Heaviest_count']
