import pickle

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold

import config
from models import LGBMModel


if __name__ == '__main__':
    X = pd.read_csv(config.preprocessed_train_path)
    X_add = pd.read_csv(config.preprocessed_test_for_train_path)
    X = pd.concat([X, X_add])

    X['hour_sin'] = X['hour'].map(lambda x: np.sin(2 * np.pi * x / 23))
    X['hour_cos'] = X['hour'].map(lambda x: np.cos(2 * np.pi * x / 23))
    X = X.drop(columns=['hour'])

    X['weekday_sin'] = X['weekday'].map(lambda x: np.sin(2 * np.pi * x / 6))
    X['weekday_cos'] = X['weekday'].map(lambda x: np.cos(2 * np.pi * x / 6))
    X = X.drop(columns=['weekday'])

    X['day_sin'] = X['day'].map(lambda x: np.sin(2 * np.pi * x / 6))
    X['day_cos'] = X['day'].map(lambda x: np.cos(2 * np.pi * x / 6))
    X = X.drop(columns=['day'])

    X['mean_time_per_day'] = X['total_time_sum'] / X['days_since_installation']
    X['current_title_mean_time'] = X['current_title_total_time'] / X['current_title_count']
    X['current_world_mean_time'] = X['current_world_total_time'] / X['current_world_count']
    X['last_mean_accuracy'] = X[['last_accuracy_Bird Measurer (Assessment)',
                                 'last_accuracy_Cart Balancer (Assessment)',
                                 'last_accuracy_Cauldron Filler (Assessment)',
                                 'last_accuracy_Chest Sorter (Assessment)',
                                 'last_accuracy_Mushroom Sorter (Assessment)']].mean(axis=1)
    X['ratio_of_life_in_game'] = X['total_time_sum'] / X['sec_since_installation']
    X['time_per_session'] = X['total_time_sum'] / X['accumulated_sessions']
    X['sessions_per_day'] = X['accumulated_sessions'] / X['days_since_installation']
    X['events_per_session'] = X['accumulated_actions'] / X['accumulated_sessions']
    X['time_per_event'] = X['total_time_sum'] / X['accumulated_actions']
    X['events_per_day'] = X['accumulated_actions'] / X['days_since_installation']

    count_cols = [col for col in X.columns if 'count' in col]
    for col in count_cols:
        X[col] = X[col] / X['accumulated_actions']
        X[col + '_Time_norm'] = X[col] / X['total_time_sum']

    X = X.replace({np.inf: 0})

    print(X.shape)

    y = X['accuracy_group']

    X = X[['accuracy_group', 'installation_id',
    'title',
 'accuracy_groups_skew',
 'title_Tree Top City - Level 3_count',
 'session_activity_len_lag',
 'event_code_4100_count',
 'current_world_activity_time',
 'event_code_4010_count',
 'assess_duration_mean',
 'day_cos',
 'title_Welcome to Lost Lagoon!_count',
 'event_code_3121_count_Time_norm',
 'titles_mode',
 'current_world_game_time',
 'session_activity_len_skew',
 'event_code_4035_count',
 'title_Magma Peak - Level 2_count',
 'world_MAGMAPEAK_count',
 'event_code_2030_count_Time_norm',
 'total_time_skew',
 'title_Tree Top City - Level 1_count',
 'title_Tree Top City - Level 2_count',
 'type_Game_count',
 'current_world_count',
 'event_code_4090_count_Time_norm',
 'current_title_mean_time',
 'title_Crystal Caves - Level 3_count',
 '3_group_count',
 'event_code_3021_count_Time_norm',
 'title_event_code_Cauldron Filler (Assessment)_3020_count',
 'title_event_code_Crystal Caves - Level 3_2000_count',
 'title_event_code_Sandcastle Builder (Activity)_4020_count_Time_norm',
 'event_code_4070_count',
 'current_title_count_Time_norm',
 'event_code_3120_count',
 'session_activity_len_max',
 'title_event_code_Chow Time_4070_count',
 'event_code_3110_count',
 'last_mean_accuracy',
 'title_event_code_Cauldron Filler (Assessment)_3120_count',
 'accuracy_groups_mean',
 'event_code_2025_count',
 'hour_sin',
 'type_Activity_count',
 'event_code_3020_count',
 'accuracies_skew',
 'title_event_code_Happy Camel_3020_count',
 'event_code_2030_count',
 'event_code_2020_count',
 'session_activity_len_std',
 'change_type_count',
 'event_code_4040_count',
 'event_code_2081_count',
 'title_event_code_Crystal Caves - Level 1_2000_count_Time_norm',
 'event_code_2075_count_Time_norm',
 'accuracy_groups_median',
 'title_event_code_Chicken Balancer (Activity)_4020_count',
 'title_Ordering Spheres_count_Time_norm',
 'MAGMAPEAK_world_total_time',
 'title_event_code_Scrub-A-Dub_3020_count',
 'title_event_code_Chow Time_3121_count_Time_norm',
 'sessions_per_day',
 'title_Chow Time_count',
 'title_event_code_Bird Measurer (Assessment)_2030_count',
 'type_Assessment_count_Time_norm',
 'mean_time_per_day',
 'event_code_4095_count_Time_norm',
 'world_NONE_count',
 'title_event_code_Dino Dive_2030_count',
 'All Star Sorting_title_total_time',
 'title_event_code_Chest Sorter (Assessment)_4025_count_Time_norm',
 'events_per_day',
 'title_event_code_Chow Time_3021_count_Time_norm',
 'title_event_code_Sandcastle Builder (Activity)_2000_count',
 'title_event_code_Scrub-A-Dub_3120_count',
 'title_event_code_Chest Sorter (Assessment)_3021_count_Time_norm',
 'title_event_code_Dino Drink_4070_count',
 'title_event_code_Bird Measurer (Assessment)_3021_count',
 'TREETOPCITY_world_activity_time',
 'weekday_5',
 'title_event_code_Mushroom Sorter (Assessment)_2010_count',
 'accumulated_correct_attempts_std',
 'assess_duration_sum',
 'Chow Time_title_total_time',
 'title_event_code_Bug Measurer (Activity)_4025_count',
 'title_event_code_Watering Hole (Activity)_4021_count',
 'title_Slop Problem_count',
 'title_event_code_Leaf Leader_3121_count',
 'title_event_code_Bug Measurer (Activity)_4035_count_Time_norm',
 'title_event_code_Flower Waterer (Activity)_4020_count',
 'title_event_code_Happy Camel_3121_count',
 'title_event_code_Slop Problem_2000_count_Time_norm',
 'title_event_code_Cart Balancer (Assessment)_4030_count',
 'title_event_code_Sandcastle Builder (Activity)_4070_count_Time_norm',
 'title_event_code_Bug Measurer (Activity)_4070_count',
 'title_event_code_Pan Balance_3020_count_Time_norm',
 'title_event_code_Happy Camel_4045_count',
 'title_event_code_Flower Waterer (Activity)_4022_count_Time_norm',
 'title_event_code_All Star Sorting_3021_count',
 'title_event_code_Chow Time_3010_count',
 'title_event_code_Chest Sorter (Assessment)_2010_count',
 'title_event_code_Air Show_3121_count',
 "title_Pirate's Tale_count_Time_norm",
 'title_event_code_All Star Sorting_3020_count',
 'accumulated_actions',
 'title_Sandcastle Builder (Activity)_count_Time_norm',
 'title_Fireworks (Activity)_count',
 'title_event_code_Fireworks (Activity)_3010_count_Time_norm',
 'CRYSTALCAVES_world_activity_time',
 'title_event_code_Cart Balancer (Assessment)_4035_count',
 'accumulated_uncorrect_attempts_sum',
 'title_event_code_Pan Balance_3120_count_Time_norm',
 'event_code_2070_count',
 'title_Rulers_count_Time_norm',
 'Chest Sorter (Assessment)_title_total_time',
 'title_event_code_Flower Waterer (Activity)_3010_count',
 'title_event_code_Cauldron Filler (Assessment)_4070_count_Time_norm',
 'title_event_code_Cauldron Filler (Assessment)_4035_count',
 'title_event_code_Cauldron Filler (Assessment)_3120_count_Time_norm',
 'event_code_2025_count_Time_norm',
 'TREETOPCITY_world_total_time',
 'title_event_code_Air Show_2030_count',
 'title_event_code_Sandcastle Builder (Activity)_3010_count_Time_norm',
 'title_event_code_Chow Time_2030_count_Time_norm',
 '1_group_count',
 'title_Lifting Heavy Things_count_Time_norm',
 'title_event_code_Bird Measurer (Assessment)_3121_count',
 'title_event_code_Chow Time_2020_count',
 'accuracy_groups_lag_1',
 'title_event_code_Bottle Filler (Activity)_2000_count',
 'title_Scrub-A-Dub_count_Time_norm',
 'title_event_code_Mushroom Sorter (Assessment)_2010_count_Time_norm',
 'title_event_code_Chest Sorter (Assessment)_4040_count',
 'title_event_code_Chow Time_4010_count',
 'title_event_code_Chow Time_3110_count',
 'title_event_code_All Star Sorting_4020_count',
 'event_code_2070_count_Time_norm',
 'title_event_code_Slop Problem_2000_count',
 'title_event_code_Cart Balancer (Assessment)_2010_count',
 'title_event_code_Sandcastle Builder (Activity)_4030_count_Time_norm',
 'title_event_code_Chest Sorter (Assessment)_4070_count',
 'title_event_code_Cauldron Filler (Assessment)_4030_count',
 'title_event_code_Mushroom Sorter (Assessment)_3020_count',
 'title_event_code_Fireworks (Activity)_3110_count_Time_norm',
 'total_time_median',
 'title_event_code_Flower Waterer (Activity)_3110_count',
 'title_event_code_Fireworks (Activity)_4020_count_Time_norm',
 'session_activity_len_median',
 'title_Chest Sorter (Assessment)_count',
 'title_event_code_Flower Waterer (Activity)_4025_count',
 'Dino Drink_title_total_time',
 'title_event_code_Flower Waterer (Activity)_4022_count',
 'title_event_code_Cauldron Filler (Assessment)_3020_count_Time_norm',
 'title_event_code_Chest Sorter (Assessment)_3121_count_Time_norm',
 'last_accuracy_group_Bird Measurer (Assessment)',
 'title_event_code_Balancing Act_2000_count',
 'MAGMAPEAK_world_game_time',
 'title_event_code_Cauldron Filler (Assessment)_4020_count',
 'weekday_4',
 'title_event_code_Chicken Balancer (Activity)_4035_count',
 'title_event_code_Watering Hole (Activity)_3010_count',
 'assess_titles_mode',
 'title_event_code_Leaf Leader_4070_count',
 'type_Clip_count_Time_norm',
 'weekday_3',
 'title_event_code_Sandcastle Builder (Activity)_4021_count_Time_norm',
 'title_event_code_Pan Balance_4010_count',
 'title_Cart Balancer (Assessment)_count',
 'title_event_code_Watering Hole (Activity)_4070_count_Time_norm',
 'titles_nunique',
 'TREETOPCITY_world_game_time',
 'title_event_code_Cart Balancer (Assessment)_4035_count_Time_norm',
 'title_event_code_Chicken Balancer (Activity)_4030_count',
 'event_code_2035_count_Time_norm',
 'title_event_code_Bird Measurer (Assessment)_2010_count',
 'title_event_code_Chow Time_3020_count',
 'weekday_0',
 'last_accuracy_group_Cauldron Filler (Assessment)',
 'title_Pan Balance_count',
 'event_code_4045_count_Time_norm',
 'title_event_code_Scrub-A-Dub_4010_count_Time_norm',
 'title_event_code_All Star Sorting_3110_count',
 'title_event_code_Rulers_2000_count_Time_norm',
 'title_event_code_Fireworks (Activity)_4070_count_Time_norm',
 'title_event_code_All Star Sorting_3121_count',
 'title_Chest Sorter (Assessment)_count_Time_norm',
 'title_event_code_Cart Balancer (Assessment)_2000_count',
 'last_accuracy_group_Chest Sorter (Assessment)',
 'title_event_code_Scrub-A-Dub_4070_count',
 'title_event_code_Happy Camel_3121_count_Time_norm',
 'accuracy_groups_sum',
 'event_code_2081_count_Time_norm',
 'accuracy_groups_lag_diff',
 'title_Rulers_count',
 'title_event_code_Watering Hole (Activity)_3110_count',
 'title_event_code_Mushroom Sorter (Assessment)_3020_count_Time_norm',
 'title_event_code_Bottle Filler (Activity)_2030_count',
 'title_event_code_Chicken Balancer (Activity)_4070_count',
 'title_event_code_Tree Top City - Level 3_2000_count_Time_norm',
 'Cauldron Filler (Assessment)_title_total_time',
 'title_event_code_Mushroom Sorter (Assessment)_2030_count',
 'assess_duration_skew',
 'title_event_code_Lifting Heavy Things_2000_count',
 'title_event_code_Dino Dive_3120_count',
 'title_event_code_Cart Balancer (Assessment)_3020_count_Time_norm',
 'Fireworks (Activity)_title_total_time',
 'title_event_code_All Star Sorting_4070_count',
 'title_Costume Box_count',
 'Flower Waterer (Activity)_title_total_time',
 'last_accuracy_Mushroom Sorter (Assessment)',
 'title_Balancing Act_count_Time_norm',
 'title_event_code_Dino Drink_3020_count',
 'weekday_cos',
 'title_event_code_Happy Camel_2030_count',
 'title_event_code_Watering Hole (Activity)_4025_count',
 'title_event_code_Mushroom Sorter (Assessment)_3120_count',
 'event_code_4220_count_Time_norm',
 'title_event_code_Cart Balancer (Assessment)_3021_count',
 'title_event_code_Sandcastle Builder (Activity)_3110_count_Time_norm',
 'title_event_code_Mushroom Sorter (Assessment)_4100_count',
 'title_event_code_All Star Sorting_2020_count',
 'title_event_code_Fireworks (Activity)_2000_count',
 'title_event_code_Flower Waterer (Activity)_4030_count',
 'hour_20',
 'title_event_code_Chow Time_4020_count',
 'title_event_code_Leaf Leader_4070_count_Time_norm',
 'title_event_code_Chest Sorter (Assessment)_4030_count_Time_norm',
 'title_Watering Hole (Activity)_count',
 'title_event_code_Cart Balancer (Assessment)_2010_count_Time_norm',
 'title_event_code_Pan Balance_2030_count',
 'title_event_code_Mushroom Sorter (Assessment)_3120_count_Time_norm',
 'title_event_code_Cart Balancer (Assessment)_3010_count',
 '1_group_count_Time_norm',
 'title_event_code_Dino Dive_3020_count',
 'title_event_code_Bubble Bath_3120_count',
 'title_Bird Measurer (Assessment)_count',
 'title_event_code_Cart Balancer (Assessment)_3110_count',
 'Mushroom Sorter (Assessment)_title_total_time',
 'title_event_code_Ordering Spheres_2000_count_Time_norm',
 'title_event_code_Scrub-A-Dub_4070_count_Time_norm',
 'title_event_code_Happy Camel_3120_count_Time_norm',
 'title_Cauldron Filler (Assessment)_count',
 'title_event_code_All Star Sorting_3010_count',
 'title_event_code_Bug Measurer (Activity)_4070_count_Time_norm',
 'title_event_code_Chow Time_3120_count',
 'title_event_code_Happy Camel_4045_count_Time_norm',
 'title_event_code_Mushroom Sorter (Assessment)_4030_count',
 'title_event_code_Dino Drink_4010_count',
 'session_activity_len_sum',
 'Watering Hole (Activity)_title_total_time',
 'accumulated_correct_attempts_skew',
 'title_Heavy_ Heavier_ Heaviest_count']]

    model = LGBMModel(params=config.lgb_params,
                      folds=GroupKFold(n_splits=config.n_folds),
                      cols_to_drop=['installation_id', 'accuracy_group'],
                      group_col='installation_id',
                      **config.lgb_train_params)

    model.fit(X, y)

    with open('./checkpoints/model.pkl', 'wb') as fout:
            pickle.dump(model, fout)
