import pickle

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold, StratifiedKFold, KFold

import config
from models import LGBMModel


if __name__ == '__main__':
    X = pd.read_csv(config.preprocessed_train_path)

    #useless_events = [2081, 2070, 2075, 4050, 4080, 4110, 4220, 2050, 4235, 2035, 5010, 4230, 5000, 2040,
    #                  4095, 2025, 2083, 2060]
    useless_event_feats = []
    #for col in X.columns:
    #    for ev in useless_events:
    #        if str(ev) in col:
    #            useless_event_feats.append(col)

    X['hour_sin'] = X['hour'].map(lambda x: np.sin(2 * np.pi * x / 23))
    X['hour_cos'] = X['hour'].map(lambda x: np.cos(2 * np.pi * x / 23))
    X = X.drop(columns=['hour'])

    X['weekday_sin'] = X['weekday'].map(lambda x: np.sin(2 * np.pi * x / 6))
    X['weekday_cos'] = X['weekday'].map(lambda x: np.cos(2 * np.pi * x / 6))
    X = X.drop(columns=['weekday'])

    X['day_sin'] = X['day'].map(lambda x: np.sin(2 * np.pi * x / 6))
    X['day_cos'] = X['day'].map(lambda x: np.cos(2 * np.pi * x / 6))
    X = X.drop(columns=['day'])

    X['mean_time_per_day'] = X['total_time'] / X['days_since_installation']
    X['current_title_mean_time'] = X['current_title_total_time'] / X['current_title_count']
    X['current_world_mean_time'] = X['current_world_total_time'] / X['current_world_count']
    X['last_mean_accuracy'] = X[['last_accuracy_Bird Measurer (Assessment)',
                                 'last_accuracy_Cart Balancer (Assessment)',
                                 'last_accuracy_Cauldron Filler (Assessment)',
                                 'last_accuracy_Chest Sorter (Assessment)',
                                 'last_accuracy_Mushroom Sorter (Assessment)']].mean(axis=1)
    X['ratio_of_life_in_game'] = X['total_time'] / X['sec_since_installation']
    X['time_per_session'] = X['total_time'] / X['accumulated_sessions']
    X['sessions_per_day'] = X['accumulated_sessions'] / X['days_since_installation']
    X['events_per_session'] = X['accumulated_actions'] / X['accumulated_sessions']
    X['time_per_event'] = X['total_time'] / X['accumulated_actions']
    X['events_per_day'] = X['accumulated_actions'] / X['days_since_installation']

    to_drop = ['event_code_4045_count',
       'title_event_code_Chicken Balancer (Activity)_4070_count',
       'title_event_code_Bottle Filler (Activity)_3110_count',
       'events_per_day',
       'title_event_code_Magma Peak - Level 1_2000_count',
       'title_event_code_All Star Sorting_3021_count',
       'title_event_code_Chow Time_3120_count',
       'title_event_code_Bug Measurer (Activity)_3010_count',
       'last_accuracy_Cart Balancer (Assessment)',
       'title_event_code_Bottle Filler (Activity)_4035_count',
       'title_event_code_Pan Balance_4070_count',
       'Chicken Balancer (Activity)_title_total_time',
       'title_event_code_Happy Camel_4020_count',
       'title_event_code_Chow Time_3010_count',
       'title_event_code_Happy Camel_4030_count',
       'title_event_code_Dino Dive_2030_count', 'event_code_2060_count',
       'last_accuracy_Bird Measurer (Assessment)',
       'title_event_code_Bug Measurer (Activity)_4035_count',
       'title_event_code_Bottle Filler (Activity)_2020_count',
       'accumulated_correct_attempts',
       'title_event_code_Tree Top City - Level 2_2000_count',
       'title_event_code_Dino Dive_3010_count',
       'accumulated_uncorrect_attempts',
       'Egg Dropper (Activity)_title_total_time', 'world_NONE_count',
       'title_event_code_Mushroom Sorter (Assessment)_4070_count',
       'title_event_code_Chow Time_4020_count',
       'title_event_code_Egg Dropper (Activity)_4020_count',
       'Bubble Bath_title_total_time', 'event_code_4095_count',
       'title_event_code_Dino Drink_4020_count',
       'title_event_code_Happy Camel_4070_count', 'event_code_2025_count',
       'title_event_code_Flower Waterer (Activity)_4030_count',
       'event_code_2083_count',
       'title_event_code_All Star Sorting_3121_count',
       'title_event_code_Flower Waterer (Activity)_4020_count',
       'title_event_code_Egg Dropper (Activity)_4070_count',
       'title_event_code_Cauldron Filler (Assessment)_4070_count',
       'title_event_code_Watering Hole (Activity)_3010_count',
       'title_event_code_Crystal Caves - Level 2_2000_count',
       'last_accuracy_Chest Sorter (Assessment)',
       'title_event_code_Chicken Balancer (Activity)_4035_count',
       'title_event_code_Flower Waterer (Activity)_4025_count',
       'title_event_code_Dino Dive_3021_count',
       'title_event_code_Watering Hole (Activity)_4020_count',
       'title_event_code_Scrub-A-Dub_2020_count',
       'title_event_code_Happy Camel_3110_count',
       'title_event_code_Chest Sorter (Assessment)_4020_count',
       'title_event_code_All Star Sorting_2020_count',
       'title_event_code_Air Show_4070_count',
       'title_event_code_Bottle Filler (Activity)_2030_count',
       'title_event_code_Pan Balance_3120_count',
       'title_event_code_All Star Sorting_4035_count',
       'Leaf Leader_title_total_time',
       'title_event_code_Happy Camel_3121_count',
       'title_Slop Problem_count',
       'title_event_code_Happy Camel_3021_count',
       'title_event_code_Cart Balancer (Assessment)_4030_count',
       'title_event_code_Watering Hole (Activity)_3110_count',
       'title_event_code_Watering Hole (Activity)_4021_count',
       'title_event_code_Scrub-A-Dub_4020_count',
       'title_event_code_Bug Measurer (Activity)_3110_count',
       'title_event_code_Flower Waterer (Activity)_3010_count',
       'event_code_4230_count', 'title_event_code_Air Show_2030_count',
       'title_event_code_Dino Drink_4031_count',
       'title_event_code_Happy Camel_3010_count',
       'Pan Balance_title_total_time',
       'title_event_code_Bubble Bath_4070_count',
       'title_Bug Measurer (Activity)_count',
       'title_event_code_Flower Waterer (Activity)_3110_count',
       'title_event_code_Egg Dropper (Activity)_3010_count',
       'Cauldron Filler (Assessment)_title_total_time',
       'title_Balancing Act_count',
       'title_event_code_Mushroom Sorter (Assessment)_2010_count',
       'title_event_code_Chest Sorter (Assessment)_4100_count',
       'Mushroom Sorter (Assessment)_title_total_time',
       'event_code_2040_count',
       'last_accuracy_Mushroom Sorter (Assessment)',
       'title_event_code_Dino Dive_3110_count',
       'title_event_code_Egg Dropper (Activity)_3110_count',
       'type_Assessment_count', 'title_Ordering Spheres_count',
       'event_code_2035_count',
       'title_event_code_Cart Balancer (Assessment)_4020_count',
       'event_code_4235_count', 'current_title_count',
       'title_event_code_Chow Time_3110_count',
       'title_event_code_Dino Dive_4020_count',
       'title_event_code_Bird Measurer (Assessment)_2030_count',
       'title_event_code_Scrub-A-Dub_3010_count',
       'title_event_code_Dino Drink_3110_count', 'event_code_5000_count',
       'title_event_code_Dino Drink_3010_count',
       'title_event_code_Leaf Leader_3121_count',
       'title_event_code_Egg Dropper (Activity)_4025_count',
       'title_event_code_Dino Dive_2020_count',
       'title_event_code_Scrub-A-Dub_2080_count',
       'title_event_code_Slop Problem_2000_count',
       'title_Chow Time_count', 'title_event_code_Dino Dive_3121_count',
       'title_event_code_Bubble Bath_4040_count',
       'title_event_code_All Star Sorting_2025_count',
       'title_event_code_Scrub-A-Dub_3110_count',
       'title_event_code_Happy Camel_2020_count', 'event_code_5010_count',
       'event_code_2081_count',
       'title_event_code_Bug Measurer (Activity)_4030_count',
       'title_event_code_Leaf Leader_4070_count',
       'title_event_code_Balancing Act_2000_count',
       'event_code_2075_count',
       'title_event_code_Chicken Balancer (Activity)_3110_count',
       'title_event_code_Scrub-A-Dub_2030_count',
       'title_event_code_Leaf Leader_3021_count',
       'title_event_code_All Star Sorting_3110_count',
       'title_event_code_Chicken Balancer (Activity)_3010_count',
       'title_event_code_Scrub-A-Dub_3020_count',
       'title_event_code_Pan Balance_2030_count',
       'title_event_code_Leaf Leader_2030_count',
       'title_event_code_Ordering Spheres_2000_count',
       'title_Honey Cake_count', 'title_event_code_Dino Drink_3021_count',
       'Air Show_title_total_time',
       'title_event_code_Bubble Bath_3010_count',
       'title_event_code_Watering Hole (Activity)_5000_count',
       'title_event_code_Bug Measurer (Activity)_2000_count',
       'title_event_code_Leaf Leader_4020_count',
       'title_12 Monkeys_count',
       'title_event_code_Bubble Bath_3110_count',
       'title_event_code_All Star Sorting_3010_count',
       'title_event_code_Dino Drink_3020_count',
       'title_event_code_Scrub-A-Dub_2040_count',
       'title_event_code_Bug Measurer (Activity)_4025_count',
       'title_event_code_Bubble Bath_3121_count',
       'Crystals Rule_title_total_time',
       'title_event_code_Scrub-A-Dub_3120_count',
       'title_event_code_Mushroom Sorter (Assessment)_3020_count',
       'title_event_code_Pan Balance_2020_count',
       'title_event_code_Leaf Leader_2020_count',
       'title_Lifting Heavy Things_count', 'title_Costume Box_count',
       'title_Chest Sorter (Assessment)_count',
       'title_event_code_Scrub-A-Dub_2083_count',
       'days_since_installation', 'event_code_2070_count',
       'title_event_code_All Star Sorting_3020_count',
       'title_event_code_All Star Sorting_3120_count',
       'title_event_code_Scrub-A-Dub_3021_count',
       'title_Scrub-A-Dub_count',
       'title_event_code_Chest Sorter (Assessment)_3120_count',
       'title_event_code_Dino Drink_3121_count',
       'title_event_code_Dino Drink_3120_count',
       "title_Pirate's Tale_count",
       'title_event_code_Cart Balancer (Assessment)_3110_count',
       'title_event_code_Bird Measurer (Assessment)_4030_count',
       'title_event_code_Mushroom Sorter (Assessment)_3120_count',
       'title_event_code_Chow Time_2000_count',
       'title_event_code_Cauldron Filler (Assessment)_4030_count',
       'event_code_2050_count', 'title_event_code_Bubble Bath_3021_count',
       'title_event_code_Crystals Rule_4070_count',
       'title_event_code_Cart Balancer (Assessment)_4100_count',
       'title_event_code_Watering Hole (Activity)_5010_count',
       'Bird Measurer (Assessment)_title_total_time',
       'title_event_code_Bubble Bath_4230_count',
       'title_event_code_Mushroom Sorter (Assessment)_4020_count',
       'title_event_code_Cart Balancer (Assessment)_2010_count',
       'title_event_code_Chest Sorter (Assessment)_3010_count',
       'title_Pan Balance_count',
       'title_event_code_Chicken Balancer (Activity)_4022_count',
       'title_event_code_Chest Sorter (Assessment)_4070_count',
       'title_event_code_Dino Dive_3020_count',
       'title_event_code_Pan Balance_3021_count',
       'title_event_code_Pan Balance_3010_count',
       'title_event_code_Honey Cake_2000_count',
       'title_event_code_Mushroom Sorter (Assessment)_2030_count',
       'title_event_code_Pan Balance_3121_count',
       'title_event_code_Mushroom Sorter (Assessment)_3021_count',
       'title_event_code_Pan Balance_4030_count',
       'title_Sandcastle Builder (Activity)_count',
       'title_event_code_Happy Camel_4045_count',
       'title_event_code_Crystals Rule_3010_count',
       'title_event_code_Cauldron Filler (Assessment)_3110_count',
       'title_event_code_12 Monkeys_2000_count',
       'title_event_code_Air Show_3010_count',
       'title_event_code_Scrub-A-Dub_2081_count',
       'title_event_code_Air Show_3110_count', 'title_Rulers_count',
       'title_event_code_Mushroom Sorter (Assessment)_3010_count',
       'title_All Star Sorting_count',
       'title_event_code_Happy Camel_2000_count',
       'title_event_code_Bird Measurer (Assessment)_4100_count',
       'title_event_code_Bird Measurer (Assessment)_3121_count',
       'title_event_code_Chest Sorter (Assessment)_3110_count',
       'title_event_code_Bubble Bath_4235_count',
       'title_Dino Drink_count',
       'title_event_code_Bird Measurer (Assessment)_3021_count',
       'title_Egg Dropper (Activity)_count', 'title_Happy Camel_count',
       'title_event_code_Mushroom Sorter (Assessment)_3121_count',
       "title_event_code_Pirate's Tale_2000_count",
       'title_event_code_Costume Box_2000_count',
       'title_event_code_Scrub-A-Dub_4010_count', 'event_code_4220_count',
       'title_event_code_Pan Balance_2000_count',
       'title_event_code_Cauldron Filler (Assessment)_3010_count',
       'title_event_code_Chow Time_4010_count',
       'title_event_code_Cart Balancer (Assessment)_3020_count',
       'title_event_code_Bird Measurer (Assessment)_4070_count',
       'title_event_code_Chest Sorter (Assessment)_3020_count',
       'title_event_code_Bird Measurer (Assessment)_4025_count',
       'title_event_code_Dino Drink_2020_count',
       'title_event_code_Dino Dive_3120_count',
       'title_event_code_Sandcastle Builder (Activity)_2000_count',
       'title_event_code_Cart Balancer (Assessment)_3010_count',
       'title_Cart Balancer (Assessment)_count',
       'title_event_code_Scrub-A-Dub_2050_count',
       'title_Bubble Bath_count', 'title_Fireworks (Activity)_count',
       'title_event_code_Lifting Heavy Things_2000_count',
       'title_event_code_Happy Camel_2080_count',
       'title_event_code_Crystals Rule_3110_count',
       'title_event_code_Air Show_2020_count',
       'title_event_code_Cart Balancer (Assessment)_2030_count',
       'title_Crystals Rule_count',
       'title_event_code_Bubble Bath_3020_count',
       'title_event_code_Leaf Leader_3120_count',
       'title_event_code_Leaf Leader_3020_count',
       'title_event_code_Pan Balance_4020_count', 'event_code_4110_count',
       'title_event_code_Happy Camel_2083_count',
       'title_event_code_Chest Sorter (Assessment)_2000_count',
       'title_event_code_Bird Measurer (Assessment)_4020_count',
       'title_event_code_Bubble Bath_4220_count',
       'title_event_code_Cart Balancer (Assessment)_2000_count',
       'title_event_code_Pan Balance_4010_count',
       'title_event_code_Bird Measurer (Assessment)_2010_count',
       'title_event_code_Egg Dropper (Activity)_2000_count',
       'title_event_code_Scrub-A-Dub_3121_count',
       'title_event_code_Mushroom Sorter (Assessment)_4030_count',
       'title_event_code_Dino Drink_2070_count', 'title_Dino Dive_count',
       'title_event_code_Air Show_3121_count',
       'title_event_code_Dino Drink_2060_count',
       'title_event_code_Pan Balance_3110_count',
       'title_event_code_Bubble Bath_3120_count',
       'title_event_code_Cauldron Filler (Assessment)_4040_count',
       'title_event_code_Chow Time_4095_count',
       'title_event_code_Bird Measurer (Assessment)_3110_count',
       'title_event_code_Crystals Rule_3020_count',
       'title_event_code_Cart Balancer (Assessment)_3121_count',
       'title_event_code_Leaf Leader_3110_count',
       'title_event_code_Leaf Leader_2075_count',
       'title_event_code_Air Show_4100_count',
       'title_event_code_Dino Dive_4010_count',
       'title_event_code_Scrub-A-Dub_2000_count',
       'title_event_code_Cauldron Filler (Assessment)_2020_count',
       'title_event_code_Cauldron Filler (Assessment)_4035_count',
       'title_event_code_Dino Dive_2000_count',
       'title_event_code_Chest Sorter (Assessment)_2020_count',
       'title_event_code_Dino Drink_2000_count',
       'title_event_code_Cart Balancer (Assessment)_4035_count',
       'title_event_code_Cart Balancer (Assessment)_4040_count',
       'title_event_code_Mushroom Sorter (Assessment)_4100_count',
       'title_event_code_Pan Balance_4035_count',
       'title_event_code_Bird Measurer (Assessment)_3010_count',
       'title_event_code_Fireworks (Activity)_2000_count',
       'title_event_code_Crystals Rule_4020_count',
       'title_event_code_Crystals Rule_2000_count',
       'title_event_code_Pan Balance_4025_count',
       'title_event_code_Air Show_4020_count',
       'title_event_code_Mushroom Sorter (Assessment)_3110_count',
       'title_event_code_Bubble Bath_2000_count',
       'title_event_code_Cauldron Filler (Assessment)_4025_count',
       'title_event_code_Bubble Bath_2020_count',
       'title_event_code_Dino Drink_2075_count',
       'title_Watering Hole (Activity)_count',
       'title_event_code_Bubble Bath_2030_count',
       'title_event_code_Rulers_2000_count',
       'title_event_code_Dino Drink_2030_count',
       'title_event_code_Crystals Rule_3120_count',
       'title_event_code_Air Show_3021_count',
       'title_event_code_Cart Balancer (Assessment)_2020_count',
       'title_event_code_Heavy_ Heavier_ Heaviest_2000_count',
       'title_event_code_Cauldron Filler (Assessment)_4020_count',
       'title_Heavy_ Heavier_ Heaviest_count',
       'title_event_code_Cauldron Filler (Assessment)_3121_count',
       'title_Chicken Balancer (Activity)_count',
       'title_event_code_Cauldron Filler (Assessment)_3021_count',
       '2_group_count', 'title_Cauldron Filler (Assessment)_count',
       'title_Leaf Leader_count',
       'title_event_code_Cauldron Filler (Assessment)_2030_count',
       'title_event_code_All Star Sorting_2000_count',
       'title_event_code_Leaf Leader_2070_count',
       'title_event_code_Bottle Filler (Activity)_2000_count',
       '1_group_count', 'title_event_code_Pan Balance_4100_count',
       'title_Air Show_count',
       'title_event_code_Egg Dropper (Activity)_2020_count',
       'title_event_code_Chest Sorter (Assessment)_4040_count',
       'title_Bottle Filler (Activity)_count',
       'title_event_code_Bubble Bath_2035_count',
       'title_event_code_Chest Sorter (Assessment)_3021_count',
       'title_event_code_Crystals Rule_2020_count',
       'title_event_code_Cauldron Filler (Assessment)_2000_count',
       'title_event_code_All Star Sorting_4010_count',
       'title_event_code_Dino Dive_2060_count',
       'title_event_code_Leaf Leader_3010_count',
       'title_event_code_Bubble Bath_2025_count',
       'title_event_code_Cauldron Filler (Assessment)_3120_count',
       'title_event_code_Chicken Balancer (Activity)_2000_count',
       'title_event_code_Cauldron Filler (Assessment)_4100_count',
       'title_event_code_Cart Balancer (Assessment)_3021_count',
       'title_event_code_Leaf Leader_2060_count',
       'title_event_code_Cauldron Filler (Assessment)_3020_count',
       'title_event_code_Bubble Bath_4045_count',
       'title_event_code_Dino Drink_4010_count',
       'title_event_code_Happy Camel_2081_count',
       'title_event_code_Bird Measurer (Assessment)_2020_count',
       'title_event_code_Air Show_3120_count',
       'title_event_code_Fireworks (Activity)_4090_count',
       'title_event_code_Bird Measurer (Assessment)_4110_count',
       'title_event_code_Crystals Rule_3121_count',
       'title_event_code_Crystals Rule_2030_count',
       'title_event_code_Happy Camel_4010_count',
       'title_event_code_Crystals Rule_4010_count',
       'title_Flower Waterer (Activity)_count',
       'title_event_code_Air Show_4010_count',
       'title_event_code_Cart Balancer (Assessment)_3120_count',
       'title_event_code_Cauldron Filler (Assessment)_2010_count',
       'title_event_code_Watering Hole (Activity)_2000_count',
       'title_event_code_Mushroom Sorter (Assessment)_4040_count',
       'title_event_code_Bubble Bath_4095_count',
       'title_event_code_Bubble Bath_2080_count',
       'title_event_code_Crystals Rule_3021_count',
       'title_event_code_Air Show_2000_count',
       'title_event_code_Pan Balance_4090_count',
       'title_event_code_Bubble Bath_4020_count',
       'title_event_code_Mushroom Sorter (Assessment)_2020_count',
       'title_event_code_Dino Dive_2070_count',
       'title_event_code_Flower Waterer (Activity)_2000_count',
       'title_event_code_Leaf Leader_2000_count',
       'title_event_code_Sandcastle Builder (Activity)_4090_count',
       'title_Treasure Map_count',
       'title_event_code_Chest Sorter (Assessment)_4035_count',
       'title_Mushroom Sorter (Assessment)_count',
       'title_event_code_Mushroom Sorter (Assessment)_2025_count',
       'title_event_code_Air Show_2060_count',
       'title_event_code_Leaf Leader_4010_count',
       'title_Bird Measurer (Assessment)_count',
       'title_event_code_Air Show_2070_count',
       'title_event_code_Mushroom Sorter (Assessment)_4025_count',
       'title_event_code_Happy Camel_4095_count',
       'title_event_code_Treasure Map_2000_count',
       'title_event_code_Bird Measurer (Assessment)_3020_count',
       'title_event_code_Mushroom Sorter (Assessment)_2035_count',
       'title_event_code_Chest Sorter (Assessment)_3121_count',
       'title_event_code_Bubble Bath_4010_count',
       'title_event_code_All Star Sorting_4095_count',
       'title_event_code_Air Show_3020_count',
       'title_event_code_Bird Measurer (Assessment)_3120_count',
       'title_event_code_Air Show_4110_count',
       'title_event_code_Mushroom Sorter (Assessment)_2000_count',
       'title_event_code_Chest Sorter (Assessment)_2010_count',
       'title_event_code_Bird Measurer (Assessment)_2000_count',
       'title_event_code_Air Show_2075_count',
       'title_event_code_Happy Camel_4035_count',
       'title_event_code_Bubble Bath_2083_count',
       'title_event_code_Chest Sorter (Assessment)_2030_count',
       'title_event_code_Watering Hole (Activity)_4090_count',
       'title_event_code_Crystals Rule_4050_count',
       'title_event_code_Dino Drink_4080_count',
       'Honey Cake_title_total_time',
       'Heavy_ Heavier_ Heaviest_title_total_time',
       'title_event_code_Scrub-A-Dub_4090_count',
       'Lifting Heavy Things_title_total_time',
       'title_event_code_Leaf Leader_4090_count',
       'title_event_code_Leaf Leader_4095_count',
       'title_event_code_Bottle Filler (Activity)_2010_count',
       'title_event_code_Bird Measurer (Assessment)_4090_count',
       'title_event_code_Bird Measurer (Assessment)_4080_count',
       'title_event_code_Scrub-A-Dub_4080_count',
       'title_event_code_Air Show_4090_count',
       'title_event_code_Air Show_4080_count',
       'Magma Peak - Level 1_title_total_time',
       'title_event_code_Chicken Balancer (Activity)_4090_count',
       'Crystal Caves - Level 1_title_total_time',
       'Crystal Caves - Level 3_title_total_time',
       'Crystal Caves - Level 2_title_total_time',
       '12 Monkeys_title_total_time',
       'title_event_code_Flower Waterer (Activity)_4090_count',
       'title_event_code_Flower Waterer (Activity)_4080_count',
       'Balancing Act_title_total_time',
       'title_event_code_All Star Sorting_4090_count',
       'title_event_code_Fireworks (Activity)_4080_count',
       'title_event_code_All Star Sorting_4080_count',
       'title_event_code_Egg Dropper (Activity)_4090_count',
       'title_event_code_Egg Dropper (Activity)_4080_count',
       'title_event_code_Bird Measurer (Assessment)_4035_count',
       'title_event_code_Bird Measurer (Assessment)_4040_count',
       'title_event_code_Dino Drink_4090_count',
       'title_event_code_Watering Hole (Activity)_2010_count',
       'Costume Box_title_total_time',
       'title_event_code_Dino Dive_4090_count',
       'Magma Peak - Level 2_title_total_time',
       'title_event_code_Dino Dive_4080_count',
       'NONE_world_activity_time',
       'title_event_code_Bug Measurer (Activity)_4090_count',
       'title_event_code_Cart Balancer (Assessment)_4090_count',
       'title_event_code_Sandcastle Builder (Activity)_4080_count',
       'title_event_code_Cauldron Filler (Assessment)_4080_count',
       'title_event_code_Sandcastle Builder (Activity)_2010_count',
       'title_event_code_Crystals Rule_2010_count',
       'title_event_code_Cauldron Filler (Assessment)_4090_count',
       'title_event_code_Mushroom Sorter (Assessment)_4035_count',
       'title_event_code_Happy Camel_4090_count', 'event_code_4080_count',
       'title_event_code_Pan Balance_4080_count', 'event_code_4050_count',
       'title_event_code_Mushroom Sorter (Assessment)_4090_count',
       'title_event_code_Chow Time_4090_count',
       'title_event_code_Chow Time_4080_count',
       'title_event_code_Pan Balance_2010_count',
       'title_event_code_Chest Sorter (Assessment)_4080_count',
       'title_event_code_Chest Sorter (Assessment)_4090_count',
       'title_event_code_Cart Balancer (Assessment)_4080_count',
       'title_event_code_Bug Measurer (Activity)_4080_count',
       'NONE_world_game_time', 'title_event_code_Bubble Bath_4090_count',
       'NONE_world_total_time', 'Ordering Spheres_title_total_time',
       'title_event_code_Chicken Balancer (Activity)_4080_count',
       "Pirate's Tale_title_total_time", 'Rulers_title_total_time',
       'title_event_code_Leaf Leader_4080_count',
       'title_event_code_Happy Camel_4080_count',
       'Slop Problem_title_total_time',
       'title_event_code_Bottle Filler (Activity)_4080_count',
       'title_event_code_Bottle Filler (Activity)_4090_count',
       'Treasure Map_title_total_time',
       'Tree Top City - Level 1_title_total_time',
       'Tree Top City - Level 2_title_total_time',
       'Tree Top City - Level 3_title_total_time',
       'Welcome to Lost Lagoon!_title_total_time',
       'title_event_code_Crystals Rule_4090_count',
       'title_event_code_Bubble Bath_4080_count',
       'title_event_code_Mushroom Sorter (Assessment)_4080_count']
    cols_to_drop = [col for col in X.columns if ('event_id' in col or col in to_drop)]

    X = X.drop(columns=cols_to_drop + useless_event_feats)

    print(X.shape)

    y = X['accuracy_group']

    model = LGBMModel(params=config.lgb_params,
                      folds=GroupKFold(n_splits=config.n_folds),  # shuffle=True, random_state=73),
                      cols_to_drop=['installation_id', 'accuracy_group'],
                      group_col='installation_id',
                      **config.lgb_train_params)

    model.fit(X, y)

    with open('./checkpoints/model.pkl', 'wb') as fout:
            pickle.dump(model, fout)
